document.write("自然对数：" + Math.E)
document.write("<br>")
document.write("圆周率：" + Math.PI)
document.write("<br>")
document.write("-1的绝对值(Math.abs)：" + Math.abs(-1))
document.write("<br>")
document.write("10, 100取较小值(Math.min)：" + Math.min(12, 100))
document.write("<br>")
document.write("10, 100取较大值(Math.max)：" + Math.max(12, 100))
document.write("<br>")
document.write("求幂3的4次方(Math.pow)：" + Math.pow(3, 4))
document.write("<br>")
document.write("四舍五入取整13.6(Math.round)：" + Math.round(13.6))
document.write("<br>")
document.write("0-1取随机数(Math.random)：" + Math.random())
document.write("<br>")
document.write("5-10取随机数(Math.random)：" + (Math.round(Math.random() * 5) + 5))
