x = new Number(123)
document.write("数字对象x的值：" + x)
document.write("<br/>")
document.write("数字对象x的类型：" + typeof x)
document.write("<br/>")
y = 123
document.write("基本类型y的值：" + y)
document.write("<br/>")
document.write("基本类型y的类型：" + typeof y)

document.write("<br/>")
document.write("Number对象的最小值：" + Number.MIN_VALUE)
document.write("<br/>")
document.write("Number对象的最大值：" + Number.MAX_VALUE)

a = new Number("123")
document.write("<br/>")
document.write("<br/>")
document.write("数字对象123的科学计数法表达为：" + a.toExponential())
document.write("<br/>")
document.write("数字对象123的保留两位小数表达为：" + a.toFixed(2))
b = new Number("3.1415926")
document.write("<br/>")
document.write("数字对象PI的保留三位小数表达为：" + b.toFixed(3))

a = new Number("123abc")
document.write("<br/>")
document.write("<br/>")
document.write("通过非数字字符串123abc创建出来的对象为" + a)
document.write("<br/>")
document.write("通过a==Number.NaN返回：" + (a == Number.NaN))
document.write("<br/>")
document.write("正确判断是否为NaN,调用isNaN(a),返回：" + isNaN(a))

a = new Number("123")
b = a.valueOf()
document.write("<br/>")
document.write("<br/>")
document.write("对象a的类型为：" + typeof a)
document.write("<br/>")
document.write("对象a通过valueOf()返回的值类型为：" + typeof b)
